button_inputs.py, logger.py, relay_control.py
=> Fixes log file bug

button_inputs.py, relay_control.py
improve OS check for non-RPi but Linux systems for test to avoid importing gpiozero
=> Improve OS check

greenonbrown.py
add in CLI functionality for key features
=> add argparse, replace headless with show-display

greenonbrown.py
add auto whitebalance flags as an option. Matches with options provided in official [picamera docs](https://picamera.readthedocs.io/en/release-1.13/api_camera.html#picamera.PiCamera.awb_mode).
=> add awb-mode flags

greenonbrown.py
adds sensor_mode and framerate flags to greenonbrown.py
=> add sensor_mode and framerate flags

video_analysis.py
=> update analysis for single frames

video_analysis.py
Added the ability to analyse videos for detection size (pixel, calibrated), returning a CSV of values for each video. Can specify number of frame samples per video.
=> Add detection size analysis

greenonbrown.py, image_sampler.py, video_analysis.py
Adds ability to:
* sample the image for every bounding box detection made and save to specified directory
* save whole images with frame number
plus a bit of code cleaning. Still needs integrating with main script - this is only for the video analysis code.
=> update image sampling for video analysis

README.md, greenonbrown.py
Add image sampling into the main greenonbrown.py script with documentation. With this change, the OWL can be used very easily to collect data.
=> Image sampling

video_analysis.py
update blur analysis so it's in-line with functionality of size analysis.
=> update blur analysis

README.md, greenonbrown.py, greenongreen.py, models/install_coral.sh, models/labels.txt, non_rpi_requirements.txt, owl.py, relay_control.py, requirements.txt, utils/cli_vis.py
Major updates in this pull request:
1. Move from running `greenonbrown.py` to using an `owl.py` file with GreenOnBown and GreenOnGreen classes.
2. Add and test the installation of the Google Coral for running .tflite model files
3. Fix bugs in previous code and neaten up
4. Add in explanation of the new system and update README with new files.
=> add green-on-green functionality

utils/blur_algorithms.py, video_analysis.py
Incorporates blur algorithms (fft blur) into the utils.blur_algorithms script. Adds support for them to video_analysis.py
=> add advanced blur algorithms

owl.py
add in better error handling for more descriptive errors in the command line
=> improve error handling

video_analysis.py
Updating import and class GreenOnBrown usage.
=> Updating video_analysis.py in order to use recent API modifications

greenongreen.py, owl.py
Improved GreenonGreen error checking with:
1. Better try/except catching and an `_handle_exceptions()` method to make it cleaner
2. Added `model_path` as a variable instead of relying on `algorithm='gog'`
3. Fixed bug when drawing bounding boxes in GreenonGreen class.
=> improve gog error checking

owl.py
re-add nozzleviz code after accidentally deleting it before.
=> add in nozzleviz

owl.py
Improve speed of actuation decision making by 10.5%. Reduces latency between frame and solenoid activation.
=> Optimise actuation

config/DAY_SENSITIVITY_1.ini, config/DAY_SENSITIVITY_2.ini, config/DAY_SENSITIVITY_3.ini, owl.py, utils/button_inputs.py, utils/greenonbrown.py, utils/relay_control.py
This pull request adds support for a basic GPIO-based controller. With three wires it is possible to:
1. Indicate image data sampling
2. Memory card status
3. Toggle detection or image sampling on/off.
Code efficiency for GoB has also been improved to increase FPS up to 48 FPS on a Raspberry Pi 4 running with 416 x 320 resolution frames. This should decrease latency between detection and actuation.
=> Add support for basic controller

dev/clean.sh, owl.py, utils/button_inputs.py, utils/relay_control.py
Add improved 'basic controller' functionality, including:
1. toggle between data recording and weed detection
2. status indicator light for each weed detected
GPIOs are assigned as:
1. REC LED --> BOARD38
2. MEM LED --> BOARD40
3. Switch --> BOARD36
4. Weed detection status LED --> BOARD37
=> Update basic controller

owl_setup.sh
Fix an issue with Wayland and X11 when setting the OWL background from the setup bash script.
=> Set bground bug

owl_setup.sh
Add sudo check to avoid being run as the root user - causes a lot of issues! Revert some changes back.
=> Fix user permissions

requirements.txt, update_owl.sh
Fixes package version and permission issues with the latest update_owl.sh script.
=> fix update_owl.sh
